// <auto-generated />
using System;
using CustoProducao.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustoProducao.Infrastructure.Migrations
{
    [DbContext(typeof(CustoProducaoDbContext))]
    [Migration("20180824131940_CriarEstruturaInicial")]
    partial class CriarEstruturaInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustoProducao.Core.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_EMPRESA")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NmEmpresa")
                        .HasColumnName("NM_EMPRESA");

                    b.Property<long>("NrCnpj")
                        .HasColumnName("NR_CNPJ");

                    b.HasKey("IdEmpresa");

                    b.ToTable("TB_EMPRESA");
                });

            modelBuilder.Entity("CustoProducao.Core.Entities.Insumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_INSUMO")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CdInsumo")
                        .HasColumnName("CD_INSUMO")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("DsInsumo")
                        .HasColumnName("DS_INSUMO");

                    b.Property<DateTime>("DtInsumoCadastro")
                        .HasColumnName("DT_INSUMO_CADASTRO");

                    b.Property<int>("IdEmpresa")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NmInsumo")
                        .HasColumnName("NM_INSUMO");

                    b.Property<decimal>("VlInsumoFrete")
                        .HasColumnName("VL_INSUMO_FRETE")
                        .HasColumnType("DECIMAL (18, 2)");

                    b.Property<decimal>("VlInsumoNota")
                        .HasColumnName("VL_INSUMO_NOTA")
                        .HasColumnType("DECIMAL (18, 2)");

                    b.HasKey("IdInsumo");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("TB_INSUMO");
                });

            modelBuilder.Entity("CustoProducao.Core.Entities.Insumo", b =>
                {
                    b.HasOne("CustoProducao.Core.Entities.Empresa", "Empresa")
                        .WithMany("Insumos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
