CREATE TABLE [dbo].[TB_INSUMO]
(
	[ID_INSUMO] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [DT_INSUMO_CADASTRO] DATETIME NOT NULL, 
    [NM_INSUMO] VARCHAR(100) NOT NULL, 
    [DS_INSUMO] VARCHAR(1000) NOT NULL, 
    [VL_INSUMO_NOTA] DECIMAL(18, 2) NOT NULL, 
    [VL_INSUMO_FRETE] DECIMAL(18, 2) NOT NULL
)
